version: '3.8'
services:
  app:
    image: my_laravel_image
    container_name: my_laravel_app
    ports:
      - "8080:9000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=my_database
      - DB_USERNAME=my_user
      - DB_PASSWORD=my_password
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: YGVYWaYFNevwdmHeyqaOpFqNvynUWaiX
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: YGVYWaYFNevwdmHeyqaOpFqNvynUWaiX
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
